"""Bundle the SPS Medcare website deliverables into one downloadable ZIP.

Run:  cd /app/backend && python make_package.py
Writes: frontend/public/sps-medcare-website-package.zip

Contents: the WordPress WXR import XML, a README with import instructions,
sitemap.xml, robots.txt and a CSV of all treatment content/costs.
"""

import csv
import io
import zipfile
from pathlib import Path

from make_wxr import ADDRESS, EMAIL, LANDLINE, PHONE, build as build_wxr
from seed import SPECIALTIES, TREATMENTS

PUBLIC = Path(__file__).parent.parent / "frontend" / "public"
XML_NAME = "sps-medcare-wordpress-import.xml"
ZIP_PATH = PUBLIC / "sps-medcare-website-package.zip"

README = f"""SPS MEDCARE — WEBSITE CONTENT PACKAGE
=====================================
Site: www.sps-medcare.com
Medical tourism facilitator — world-class medical treatment in India for
international patients.

CONTACT DETAILS USED THROUGHOUT THIS PACKAGE
--------------------------------------------
Mobile / WhatsApp : {PHONE}  (24/7 international patient desk)
Office landline   : {LANDLINE}
Email             : {EMAIL}
Office address    : {ADDRESS}


WHAT IS IN THIS ZIP
-------------------
1. {XML_NAME}
   The complete website content as a WordPress WXR 1.2 import file:
     - 6 pages ......... Home, About Us, Treatments, Services, Contact Us,
                         Countries We Serve
     - 10 treatment pages with full description, cost comparison table,
       procedures covered, leading hospitals, free inclusions and a 5-question
       FAQ block
     - 10 SEO blog posts ("<Treatment> in India: Cost, Hospitals and
       Recovery Time") for long-tail search traffic
     - 16 images as media attachments — 10 treatment photos plus the 6 site
       photos used on the live design (hero consultation, doctor & patient,
       patient care, operating theatre, airport pickup, Taj Mahal) —
       downloaded automatically by the WordPress importer, with alt text
     - A ready-made "Primary Menu" with all 6 pages in order
     - Featured image set on every page, treatment page and blog post
     - 10 specialty categories
     - Yoast SEO + Rank Math title and meta-description on every item

2. treatments.csv
   All {len(TREATMENTS)} treatments in spreadsheet form — name, specialty, cost in
   India, cost abroad, savings %, hospital stay, days in India and outcomes.
   Useful for price lists, brochures or handing to a developer.

3. sitemap.xml
   Ready-to-upload XML sitemap listing every page and treatment URL.
   Upload to your site root and submit in Google Search Console.

4. robots.txt
   Search-engine crawl rules with the sitemap reference.


HOW TO IMPORT INTO WORDPRESS (5 MINUTES)
----------------------------------------
Step 1. Install WordPress on your hosting for sps-medcare.com and activate
        any theme (a medical or business theme suits best).

Step 2. In WordPress admin go to:  Tools -> Import -> WordPress
        Click "Install Now" if the WordPress importer is not yet installed,
        then click "Run Importer".

Step 3. Choose the file {XML_NAME} from this ZIP
        and click "Upload file and import".

Step 4. On the next screen:
          - Assign posts to your existing admin user
          - IMPORTANT: tick "Download and import file attachments"
            (this pulls in all 16 images)
        Click Submit.

Step 5. Build your menu:  Appearance -> Menus
        Add Home, Treatments, Services, About Us, Contact Us and set it as
        the primary menu.

Step 6. Set the front page:  Settings -> Reading
        Choose "A static page" and select "Home".

Step 7. Upload sitemap.xml and robots.txt to your site root, then submit the
        sitemap at Google Search Console for faster indexing.


SEO NOTES
---------
- Treatment URLs use search-friendly slugs, e.g.
  /treatments/cardiac-treatment-in-india
- Every page and post carries both Yoast and Rank Math meta keys, so your
  titles and descriptions appear automatically whichever SEO plugin you use.
- The "Countries We Serve" page targets searches such as
  "medical treatment in India from Bangladesh".
- Keep the phone number {PHONE} visible in your header and
  footer — it is the primary conversion point on every page.

Generated by SPS Medcare website builder.
"""


def treatments_csv() -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "Treatment", "Specialty", "Cost in India (USD)", "Cost Abroad (USD)",
        "Savings %", "Hospital Stay", "Days in India", "Outcomes",
        "Procedures Covered", "Leading Hospitals", "Page URL",
    ])
    for t in TREATMENTS:
        writer.writerow([
            t["name"], t["specialty_name"], t["cost_india_usd"], t["cost_west_usd"],
            t["savings_percent"], t["hospital_stay"], t["stay_in_india"], t["success_rate"],
            " | ".join(t["procedures"]), " | ".join(t["top_hospitals"]),
            f"https://www.sps-medcare.com/treatments/{t['slug']}",
        ])
    return buf.getvalue()


def build_zip_bytes() -> bytes:
    """Build the full website package ZIP entirely in memory.

    Used by the /api/download/website-package endpoint so the file always
    exists in production, independent of build artifacts or .gitignore.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.txt", README)
        zf.writestr(XML_NAME, build_wxr())
        zf.writestr("treatments.csv", treatments_csv())
        for extra in ("sitemap.xml", "robots.txt"):
            path = PUBLIC / extra
            if path.exists():
                zf.writestr(extra, path.read_text(encoding="utf-8"))
    return buf.getvalue()


def main() -> None:
    data = build_zip_bytes()
    ZIP_PATH.write_bytes(data)
    print(
        f"Wrote {ZIP_PATH} ({len(data) / 1024:.0f} KB) — "
        f"{len(TREATMENTS)} treatments, {len(SPECIALTIES)} specialties"
    )


if __name__ == "__main__":
    main()
