"""Seed the SPS Medcare catalog.

Run:  cd /app/backend && python seed.py
Idempotent — safe to re-run (upserts on slug). Not imported by server.py.
"""

import asyncio
from datetime import datetime, timezone

from lib.db import db

IMG = "https://static.prod-images.emergentagent.com/jobs/3a108caa-be4a-4f2c-8726-5c86201a2ba5/images"

# Lifestyle / section imagery (Unsplash)
HERO_IMG = "https://images.unsplash.com/photo-1710074213379-2a9c2653046a?crop=entropy&cs=srgb&fm=jpg&q=85"
ICU_WARD_IMG = "https://images.unsplash.com/photo-1538108149393-fbbd81895907?crop=entropy&cs=srgb&fm=jpg&q=85"
OT_ROOM_IMG = "https://images.unsplash.com/photo-1762237798212-bcc000c00891?crop=entropy&cs=srgb&fm=jpg&q=85"
MONITORS_IMG = "https://images.unsplash.com/photo-1766299892549-b56b257d1ddd?crop=entropy&cs=srgb&fm=jpg&q=85"
WARD_IMG = "https://images.unsplash.com/photo-1512678080530-7760d81faba6?crop=entropy&cs=srgb&fm=jpg&q=85"
OT_LIGHTS_IMG = "https://images.unsplash.com/photo-1770836037350-00139eb5df96?crop=entropy&cs=srgb&fm=jpg&q=85"
WAREHOUSE_IMG = "https://images.unsplash.com/photo-1684695749267-233af13276d0?crop=entropy&cs=srgb&fm=jpg&q=85"

CATEGORIES = [
    {
        "slug": "icu-electric-beds",
        "name": "ICU & Electric Beds",
        "tagline": "Critical care & ward beds",
        "description": "Fully electric ICU beds, electric fowler beds and manual semi-fowler beds for hospitals, nursing homes and home ICU setups.",
        "image_url": ICU_WARD_IMG,
        "sort_order": 1,
    },
    {
        "slug": "ot-equipment",
        "name": "OT Equipment",
        "tagline": "Operation theatre essentials",
        "description": "LED surgical lights, hydraulic OT tables and electrosurgical generators for modern operating theatres.",
        "image_url": OT_LIGHTS_IMG,
        "sort_order": 2,
    },
    {
        "slug": "diagnostic-monitoring",
        "name": "Diagnostic & Monitoring",
        "tagline": "Vitals, ECG & oxygen therapy",
        "description": "Patient monitors, ECG machines, oxygen concentrators, suction machines and vitals devices with full after-sales support.",
        "image_url": MONITORS_IMG,
        "sort_order": 3,
    },
    {
        "slug": "hospital-furniture",
        "name": "Hospital Furniture",
        "tagline": "Ward & patient-room furniture",
        "description": "Bedside lockers, overbed tables, IV stands, medicine trolleys and examination furniture built for daily hospital use.",
        "image_url": WARD_IMG,
        "sort_order": 4,
    },
    {
        "slug": "surgical-supplies",
        "name": "Surgical Supplies",
        "tagline": "Consumables in bulk",
        "description": "Masks, gloves, gauze, syringes and instrument sets — GMP-certified consumables at wholesale rates.",
        "image_url": OT_ROOM_IMG,
        "sort_order": 5,
    },
    {
        "slug": "emergency-mobility",
        "name": "Emergency & Mobility",
        "tagline": "Wheelchairs & emergency care",
        "description": "Manual and electric wheelchairs, stretchers and emergency equipment for safe patient mobility and transport.",
        "image_url": HERO_IMG,
        "sort_order": 6,
    },
]

PRODUCTS = [
    {
        "slug": "apex-5-function-electric-icu-bed",
        "name": "Apex 5-Function Electric ICU Bed",
        "sku": "SPS-ICU-500",
        "category_slug": "icu-electric-beds",
        "short_desc": "Fully electric five-function ICU bed with one-touch CPR release, Trendelenburg positioning and battery backup for critical care units.",
        "description": "The Apex 5-function electric ICU bed is built for intensive care: independent electric control of backrest, knee rest, height and Trendelenburg/anti-Trendelenburg, with a one-touch CPR release that flattens the deck in seconds. Detachable ABS panels, collapsible side rails with nurse controls and a 250 kg safe load make it our most requested critical-care bed. Includes installation, demo and a 2-year on-site warranty across Delhi NCR.",
        "price": 89500,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Fully electric backrest, knee rest, height and Trendelenburg",
            "One-touch CPR quick-release function",
            "Detachable ABS head and foot panels",
            "Collapsible side rails with integrated nurse controls",
            "125 mm central-braking casters",
            "8-hour battery backup for power failure",
        ],
        "specs": {
            "Safe load": "250 kg",
            "Functions": "5 (backrest, knee rest, height, Trendelenburg, reverse Trendelenburg)",
            "Panels": "Detachable ABS",
            "Side rails": "Collapsible, with nurse controls",
            "Casters": "125 mm, central braking",
            "Battery backup": "8 hours",
            "Frame": "Powder-coated steel",
            "Mattress": "Optional (foam / anti-decubitus)",
        },
        "warranty": "2 Years",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/6fd12ec048002b4750c8146607a0345d3c5818deeb578fb3d458256cf6482e24.jpeg",
        "featured": True,
    },
    {
        "slug": "comfort-3-function-electric-fowler-bed",
        "name": "Comfort 3-Function Electric Fowler Bed",
        "sku": "SPS-ICU-310",
        "category_slug": "icu-electric-beds",
        "short_desc": "Three-function electric fowler bed with silent actuators — the dependable ward bed for hospitals and home ICU setups.",
        "description": "The Comfort 3-function electric fowler bed gives ward and home-care patients effortless positioning: electric backrest, knee rest and height adjustment via a silent hand set. A wooden-look ABS panel finish keeps it warm for home use while meeting hospital durability standards. Free installation and staff demo included in Delhi NCR.",
        "price": 52000,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Electric backrest, knee rest and height adjustment",
            "Silent actuators with handset + nurse panel",
            "Detachable wooden-finish ABS panels",
            "Foldable side rails",
            "4-inch noiseless casters with brakes",
            "6-hour battery backup",
        ],
        "specs": {
            "Safe load": "220 kg",
            "Functions": "3 (backrest, knee rest, height)",
            "Panels": "Wooden-finish ABS",
            "Controls": "Hand set + nurse control panel",
            "Casters": "100 mm, braked",
            "Battery backup": "6 hours",
            "Mattress": "Optional high-density foam",
        },
        "warranty": "2 Years",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/7e9c7ea7759455897eaa23eb39b8eedbc6025ba318e56f149dfe1cbe3dff4f52.jpeg",
        "featured": True,
    },
    {
        "slug": "classic-semi-fowler-manual-bed",
        "name": "Classic Semi-Fowler Manual Bed",
        "sku": "SPS-ICU-210",
        "category_slug": "icu-electric-beds",
        "short_desc": "Rugged manual semi-fowler bed with a smooth crank mechanism — dependable general-ward bedding at the best price.",
        "description": "The Classic semi-fowler manual bed is the workhorse of general wards: a smooth crank-operated backrest, closely spaced MS top bars and a powder-coated frame that shrugs off years of disinfectant washdowns. Standard legs or casters, and mattress options, are available on request.",
        "price": 14900,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Smooth crank-operated backrest (0–70°)",
            "Closely spaced MS top bars",
            "Anti-bacterial powder-coated frame",
            "100 mm casters (legs on request)",
            "IV rod provision",
        ],
        "specs": {
            "Safe load": "180 kg",
            "Operation": "Manual crank",
            "Frame": "19/25 mm MS tube, powder-coated",
            "Backrest": "0–70° semi-fowler",
            "Casters": "100 mm",
            "Finish": "Anti-bacterial powder coat",
        },
        "warranty": "18 Months",
        "certification": "ISO 13485:2016",
        "image_url": f"{IMG}/055d341efece07e13ab0ec87af43038a2403e533564a2b52d92dcb11d0a36279.jpeg",
        "featured": False,
    },
    {
        "slug": "lumina-led-mobile-ot-light",
        "name": "Lumina LED Mobile OT Light",
        "sku": "SPS-OT-700",
        "category_slug": "ot-equipment",
        "short_desc": "Shadow-free LED surgical light on a mobile stand — 1,20,000 lux of cool, adjustable illumination for minor OTs and clinics.",
        "description": "The Lumina LED mobile OT light delivers 1,20,000 lux of shadow-free, cool white illumination exactly where the surgeon needs it. Ninety-six high-power LEDs run cool, keep true tissue colour, and dim across a 3500–5000 K range; the weighted mobile base and gas-spring arm make it perfect for minor OTs, dental operatories and procedure rooms.",
        "price": 78000,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "96 high-power LEDs, 1,20,000 lux at 1 m",
            "Adjustable colour temperature 3500–5000 K",
            "Sterilisable central handle",
            "Gas-spring arm with smooth articulation",
            "Weighted mobile base with casters",
            "Cool light — minimal heat radiation",
        ],
        "specs": {
            "Illuminance": "1,20,000 lux @ 1 m",
            "LEDs": "96",
            "Colour temperature": "3500–5000 K adjustable",
            "Spot diameter": "15–25 cm",
            "Arm": "Gas spring, 360° rotation",
            "Power": "220 V AC / 110 V option",
            "CRI": "≥ 95",
        },
        "warranty": "2 Years",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/9948ec83466393940dbb90d65664395fd5d5d7b41e7b8e0edf1cd84f62b974e3.jpeg",
        "featured": True,
    },
    {
        "slug": "medtable-hydraulic-ot-table",
        "name": "MedTable Hydraulic OT Table",
        "sku": "SPS-OT-810",
        "category_slug": "ot-equipment",
        "short_desc": "Hydraulic operation theatre table with radiolucent top, kidney bridge and full C-arm access for general surgery.",
        "description": "The MedTable hydraulic OT table covers general, orthopaedic, gynaecological and urological procedures with a hydraulic height column, removable kidney bridge and ±25° Trendelenburg. The radiolucent top and stainless base allow unobstructed C-arm imaging, and the full set of sectional pads is autoclavable.",
        "price": 96000,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Hydraulic height adjustment 75–100 cm",
            "Removable kidney bridge",
            "±25° Trendelenburg / reverse Trendelenburg",
            "Radiolucent top for C-arm imaging",
            "Autoclavable sectional pads",
            "Stainless steel base with casters",
        ],
        "specs": {
            "Tabletop": "195 × 55 cm",
            "Height range": "75–100 cm",
            "Safe load": "180 kg",
            "Trendelenburg": "±25°",
            "Kidney bridge": "Removable, 8 cm lift",
            "Base": "Stainless steel, on casters",
        },
        "warranty": "2 Years",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/9cd7c50d831d8f5bdc04ea2384691d303d2bb124b59bba1d993b6850081f54f6.jpeg",
        "featured": False,
    },
    {
        "slug": "precision-400w-cautery-generator",
        "name": "Precision 400W Electrosurgical Generator",
        "sku": "SPS-OT-830",
        "category_slug": "ot-equipment",
        "short_desc": "400 W solid-state electrosurgical unit with cut and coagulation modes, monopolar and bipolar outputs and REM safety monitoring.",
        "description": "The Precision 400 W generator gives surgeons clean cutting and precise haemostasis across pure cut, blend, contact coag and fulguration modes, with independent monopolar and bipolar outputs. Return-electrode monitoring (REM) and isolated RF output keep the patient safe, while the self-diagnostic panel flags faults instantly.",
        "price": 68500,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "400 W solid-state RF generator",
            "Pure cut, blend, contact coag, fulguration modes",
            "Independent monopolar and bipolar outputs",
            "Return-electrode monitoring (REM)",
            "Audible + visual alarm panel",
            "Foot switch and accessories included",
        ],
        "specs": {
            "Max output": "400 W",
            "Modes": "Cut / Blend / Coag / Fulgurate / Bipolar",
            "Outputs": "Monopolar + bipolar",
            "Safety": "REM, isolated RF output",
            "Power": "220 V AC, 50 Hz",
            "Dimensions": "38 × 27 × 13 cm",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/28b088e773082831e0972e98634efdf3a334be7f7f2d3ee90a16b794200efeef.jpeg",
        "featured": False,
    },
    {
        "slug": "vitalscan-15-patient-monitor",
        "name": "VitalScan 15 Multi-Parameter Patient Monitor",
        "sku": "SPS-DM-100",
        "category_slug": "diagnostic-monitoring",
        "short_desc": "15-inch multi-parameter monitor tracking ECG, SpO2, NIBP, respiration and temperature with 72-hour trend storage.",
        "description": "The VitalScan 15 tracks every critical parameter — 5-lead ECG, SpO2, NIBP, respiration and dual temperature — on a bright 15-inch display with up to eight waveforms. Seventy-two hours of trend storage, configurable alarms and 12 hours of built-in battery keep watch through ward rounds and transfers alike. Wall mount and rolling stand included.",
        "price": 42000,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "15-inch colour LED display, up to 8 waveforms",
            "5-lead ECG with arrhythmia analysis",
            "SpO2, NIBP, respiration and dual temperature",
            "72-hour full-disclosure trends",
            "Configurable audible + visual alarms",
            "12-hour internal battery",
        ],
        "specs": {
            "Display": "15-inch colour LED",
            "Parameters": "ECG, SpO2, NIBP, RESP, TEMP × 2",
            "Waveforms": "Up to 8 simultaneous",
            "Trend storage": "72 hours",
            "Battery": "12 hours (fully charged)",
            "Mounting": "Rolling stand + wall mount included",
        },
        "warranty": "2 Years",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/fb86fb5809fcf43bc6c8b723254035988578a28f5b3cbc5d4299ee3ee87367ac.jpeg",
        "featured": True,
    },
    {
        "slug": "cardiograph-12-ecg-machine",
        "name": "CardioGraph 12-Channel ECG Machine",
        "sku": "SPS-DM-110",
        "category_slug": "diagnostic-monitoring",
        "short_desc": "12-channel digital ECG with 8.4-inch touch display, auto interpretation and 80 mm thermal printer.",
        "description": "The CardioGraph 12 records a crisp 12-lead ECG in one pass, interprets it automatically, and prints on a built-in 80 mm thermal printer. The 8.4-inch touchscreen, one-touch rhythm leads and 1000-study internal storage make it the fastest ECG workflow for clinics, wards and health camps.",
        "price": 36500,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Simultaneous 12-lead acquisition",
            "8.4-inch colour touchscreen",
            "Auto interpretation + measurements",
            "Built-in 80 mm thermal printer",
            "1000-study internal storage",
            "AC operation + 4-hour battery",
        ],
        "specs": {
            "Leads": "12 (simultaneous)",
            "Display": "8.4-inch colour touch",
            "Printer": "80 mm thermal, 3 report formats",
            "Storage": "1000 ECG records",
            "Battery": "4 hours / 300 prints",
            "Interfaces": "USB, LAN, DICOM-ready",
        },
        "warranty": "2 Years",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/92de75ab39e49a238df99ff0d1e70a5fcd6c54d4d307175968ac229db3094a53.jpeg",
        "featured": True,
    },
    {
        "slug": "oxyflow-10-oxygen-concentrator",
        "name": "OxyFlow 10 LPM Oxygen Concentrator",
        "sku": "SPS-DM-120",
        "category_slug": "diagnostic-monitoring",
        "short_desc": "Continuous-flow 10 LPM oxygen concentrator with purity alarm — ideal for home ICU setups and long-term oxygen therapy.",
        "description": "The OxyFlow 10 delivers a continuous 1–10 litres per minute of 93% ±3 oxygen without refills — just plug it in. A low-purity alarm, power-failure alarm and nebuliser port make it the standard choice for home ICU setups, and at under 48 dB it stays quiet through the night. Delivery, demo and annual servicing available across Delhi NCR.",
        "price": 58000,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Continuous flow 1–10 LPM at 93% ±3 purity",
            "Low-oxygen-purity alarm",
            "Power-failure alarm",
            "Built-in nebuliser port",
            "Quiet < 48 dB operation",
            "4 casters with handle for room-to-room use",
        ],
        "specs": {
            "Flow": "1–10 LPM continuous",
            "Oxygen purity": "93% ±3%",
            "Noise": "< 48 dB",
            "Weight": "24 kg",
            "Power": "350 W, 220 V",
            "Alarms": "Low purity, power failure, flow",
        },
        "warranty": "3 Years (compressor 5 Years)",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/45a56b36f75e187cf2e63bf674a81253a33bca5dac1305e9552edbbd8c8f512c.jpeg",
        "featured": True,
    },
    {
        "slug": "vacuuflow-portable-suction-machine",
        "name": "VacuFlow Portable Suction Machine",
        "sku": "SPS-DM-130",
        "category_slug": "diagnostic-monitoring",
        "short_desc": "Oil-free portable suction machine with 1 L autoclavable jar and adjustable vacuum — for wards, dental and home care.",
        "description": "The VacuFlow portable suction unit gives instant, adjustable vacuum for airway clearance, post-operative care and dental use. The oil-free pump needs zero maintenance, the 1-litre jar is autoclavable, and the whole unit rolls wherever the patient is — or tucks into a carry bag for home visits.",
        "price": 12500,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Oil-free maintenance-free pump",
            "Adjustable vacuum with gauge",
            "1 L autoclavable collection jar",
            "Overflow protection valve",
            "Rolling base + carry handle",
        ],
        "specs": {
            "Vacuum": "0 to -0.75 bar (adjustable)",
            "Jar": "1000 ml autoclavable",
            "Noise": "< 55 dB",
            "Weight": "4.5 kg",
            "Power": "90 W, 220 V",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/58d0988e4009f5017d86a87097d69acc67076f03af94656dcc4a09ead07c9d80.jpeg",
        "featured": False,
    },
    {
        "slug": "fingertip-pulse-oximeter-oled",
        "name": "Fingertip Pulse Oximeter (OLED)",
        "sku": "SPS-DM-140",
        "category_slug": "diagnostic-monitoring",
        "short_desc": "Compact fingertip oximeter with bright OLED display, four-direction reading and low-perfusion mode.",
        "description": "A clinic-grade fingertip pulse oximeter that reads SpO2 and pulse rate in under 8 seconds, even at low perfusion. The bright OLED flips through four display directions, the lanyard hole makes it travel-friendly, and auto-sleep saves the batteries between checks.",
        "price": 1499,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "SpO2 + pulse rate in ~8 seconds",
            "Bright four-direction OLED display",
            "Low-perfusion measurement mode",
            "Perfusion index on screen",
            "Auto-sleep power saving",
        ],
        "specs": {
            "SpO2 range": "70–99%",
            "Pulse rate": "30–250 bpm",
            "Display": "OLED, 4 directions",
            "Battery": "2 × AAA",
            "Weight": "45 g",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/bdd15e90763187104a4063b28b9d13312bd6d4fb585835144f23867441d412c8.jpeg",
        "featured": False,
    },
    {
        "slug": "abs-bedside-locker-deluxe",
        "name": "ABS Bedside Locker (Deluxe)",
        "sku": "SPS-HF-011",
        "category_slug": "hospital-furniture",
        "short_desc": "Deluxe ABS bedside locker with top tray, drawer and enclosed cabinet — hygienic, rust-proof and easy to clean.",
        "description": "The Deluxe ABS bedside locker keeps a patient's essentials tidy: a flat top tray for meals, a smooth-glide drawer and an enclosed cabinet below. moulded ABS body is fully rust-proof and wipes clean in seconds — no crevices, no corrosion, no rust stains on floors.",
        "price": 3800,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Moulded ABS body — rust-proof",
            "Flat top meal tray",
            "Smooth-glide drawer + cabinet",
            "Internal shelf",
            "4 silent casters (2 braked)",
        ],
        "specs": {
            "Body": "Moulded ABS",
            "Size": "45 × 40 × 80 cm",
            "Storage": "Drawer + cabinet with shelf",
            "Casters": "4 × 50 mm, 2 braked",
            "Colours": "White / blue",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016",
        "image_url": f"{IMG}/8138cec8feb3ec2fcdb7f4f4de85475ff62971b6a59d1bbe5fddc2557800f66c.jpeg",
        "featured": False,
    },
    {
        "slug": "adjustable-overbed-table",
        "name": "Adjustable Overbed Table",
        "sku": "SPS-HF-012",
        "category_slug": "hospital-furniture",
        "short_desc": "Height-adjustable overbed table with wood-grain laminate top and H-base — for meals, laptops and bedside nursing care.",
        "description": "The overbed table glides over any bed or wheelchair: a gas-assist column lifts the wood-grain laminate top from 72 to 105 cm with one hand, and the low H-base slides under the frame. Ideal for meals, reading, laptops and dressing changes at home or on the ward.",
        "price": 4200,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Gas-assist height adjustment 72–105 cm",
            "Wood-grain laminate top, spill-proof edge",
            "Low H-base slides under beds",
            "Tilt-top option available",
            "4 casters, 2 with brakes",
        ],
        "specs": {
            "Top": "75 × 42 cm laminate",
            "Height": "72–105 cm",
            "Base": "Powder-coated steel H-base",
            "Load": "15 kg distributed",
            "Casters": "4 × 50 mm",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016",
        "image_url": f"{IMG}/1dad7ac65f11caa2b47b5129e86560069f9e2e29e19d5d9694cb7f3c7b2bcb50.jpeg",
        "featured": False,
    },
    {
        "slug": "ss-iv-stand-4-hook",
        "name": "Stainless Steel IV Stand (4-Hook)",
        "sku": "SPS-HF-013",
        "category_slug": "hospital-furniture",
        "short_desc": "Height-adjustable stainless steel IV stand with four hooks and a stable five-leg base.",
        "description": "A classic stainless steel IV stand built for daily ward duty: four heavy hooks, a smooth telescopic column from 160 to 210 cm, and a five-leg base that stays planted even with four full fluid bags. All-stainless construction wipes clean and never rusts.",
        "price": 1850,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Four heavy-duty fluid hooks",
            "Telescopic column 160–210 cm",
            "Five-leg stable base",
            "All-stainless construction",
            "Optional: 2-shelf tray attachment",
        ],
        "specs": {
            "Height": "160–210 cm adjustable",
            "Hooks": "4",
            "Material": "Stainless steel 202",
            "Base": "5-leg, powder-coated",
            "Load": "8 kg distributed",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016",
        "image_url": f"{IMG}/9feaaa3bb8c5745206657007bd6fc84be6a23b4bcc74e7215dd6b12809f599ba.jpeg",
        "featured": False,
    },
    {
        "slug": "ss-medicine-trolley-3-shelf",
        "name": "SS Medicine Trolley (3-Shelf)",
        "sku": "SPS-HF-016",
        "category_slug": "hospital-furniture",
        "short_desc": "Three-shelf stainless steel medicine trolley with guard rails and 100 mm casters for smooth ward rounds.",
        "description": "The three-shelf SS medicine trolley carries a full ward round: three generous trays with raised guard rails, a push handle on both ends and 100 mm casters that roll quietly over thresholds. Stainless steel throughout — autoclave-friendly, rust-proof and hospital-cleanable.",
        "price": 9800,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Three stainless steel shelves",
            "Raised guard rails on all sides",
            "Push handles both ends",
            "100 mm noiseless casters (2 braked)",
            "Optional: rail-mounted waste bag holder",
        ],
        "specs": {
            "Shelves": "3",
            "Size": "85 × 48 × 90 cm",
            "Material": "Stainless steel 202/304",
            "Casters": "100 mm, 2 braked",
            "Load": "30 kg distributed",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016",
        "image_url": f"{IMG}/24b50149780435a9ac570ee23d4ab457a8ae5577bd42e111a4e815b804df1f43.jpeg",
        "featured": False,
    },
    {
        "slug": "3ply-surgical-face-mask-box-50",
        "name": "3-Ply Surgical Face Mask (Box of 50)",
        "sku": "SPS-SS-021",
        "category_slug": "surgical-supplies",
        "short_desc": "Three-ply surgical masks with ≥95% bacterial filtration and soft ear loops — box of 50, GMP certified.",
        "description": "GMP-certified three-ply surgical masks with a melt-blown filter layer rated ≥95% bacterial filtration efficiency. Soft skin-friendly ear loops, an adjustable nose clip and a breathable pleated fit — supplied by the box (50 masks) or carton (2000 masks) at wholesale rates.",
        "price": 180,
        "price_unit": "box",
        "moq": "10 Boxes",
        "features": [
            "BFE ≥ 95% melt-blown filter layer",
            "Adjustable nose clip",
            "Soft, latex-free ear loops",
            "3-layer breathable pleats",
            "Carton pricing available (2000 masks)",
        ],
        "specs": {
            "BFE": "≥ 95%",
            "Plies": "3",
            "Pieces": "50 per box",
            "Certification": "GMP, CE",
            "Sizes": "Adult standard",
        },
        "warranty": "—",
        "certification": "GMP, CE",
        "image_url": f"{IMG}/60960c82a93193b7fbad0ce6bbf50af56d232f5721cdcd663f23223606004804.jpeg",
        "featured": False,
    },
    {
        "slug": "nitrile-examination-gloves-box-100",
        "name": "Nitrile Examination Gloves (Box of 100)",
        "sku": "SPS-SS-022",
        "category_slug": "surgical-supplies",
        "short_desc": "Powder-free, latex-free nitrile examination gloves with textured fingertips — box of 100.",
        "description": "Medical-grade nitrile examination gloves with textured fingertips for confident grip in wet procedures. Powder-free and latex-free, so they are safe for latex-allergic staff and patients alike; the 5 g nitrile film resists snags while keeping full tactile feel. Available S–XL by the box or carton.",
        "price": 650,
        "price_unit": "box",
        "moq": "5 Boxes",
        "features": [
            "Powder-free and latex-free",
            "Textured fingertips for wet grip",
            "5 g snag-resistant nitrile film",
            "Ambidextrous, beaded cuff",
            "Sizes S–XL, carton rates available",
        ],
        "specs": {
            "Material": "Synthetic nitrile",
            "Pieces": "100 per box",
            "AQL": "1.5",
            "Sizes": "S / M / L / XL",
            "Certification": "CE, ISO 13485",
        },
        "warranty": "—",
        "certification": "CE, ISO 13485",
        "image_url": f"{IMG}/6d1aed4153dd7140e4462489fefb7779047d710b77c3e915a587bfe214cce455.jpeg",
        "featured": False,
    },
    {
        "slug": "minor-ot-instrument-set-24",
        "name": "Minor OT Instrument Set (24 Pcs)",
        "sku": "SPS-SS-025",
        "category_slug": "surgical-supplies",
        "short_desc": "24-piece stainless steel minor surgery set — scissors, forceps, needle holders and scalpels in a roll-up case.",
        "description": "A complete 24-piece minor OT set for suturing, wound care and small procedures: needle holders, artery forceps, dissecting scissors, scalpel handles, tissue forceps and more in autoclavable stainless steel — all rolled into a zippered case that keeps every instrument in place and rust-free.",
        "price": 15500,
        "price_unit": "set",
        "moq": "1 Set",
        "features": [
            "24 essential minor-surgery instruments",
            "Autoclavable stainless steel (SS 420)",
            "German-style needle holders",
            "Zippered roll-up case",
            "Individual replacement pieces available",
        ],
        "specs": {
            "Pieces": "24",
            "Material": "Stainless steel 420",
            "Case": "Zippered roll-up",
            "Sterilisation": "Autoclave 134 °C",
            "Use": "Suturing, I&D, wound care",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/73b53ec94d325e4126ade15d53fa02e9aaab31fbe9fa7e0fbe5a11582922a18d.jpeg",
        "featured": False,
    },
    {
        "slug": "chrome-folding-wheelchair",
        "name": "Chrome Folding Manual Wheelchair",
        "sku": "SPS-EM-031",
        "category_slug": "emergency-mobility",
        "short_desc": "Lightweight folding wheelchair with chrome frame, 24-inch rear wheels and detachable footrests.",
        "description": "The chrome folding wheelchair folds flat in one pull and lifts into a car boot with ease. A chrome-plated steel frame carries up to 100 kg, 24-inch mag wheels roll smoothly over Indian roads and footpaths, and the detachable footrests make transfers simpler for patients and attendants.",
        "price": 6800,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Folds flat in one pull",
            "Chrome-plated steel frame",
            "24-inch mag rear wheels",
            "Detachable, swing-away footrests",
            "Companion push handles + hand brakes",
            "Attendant-release brakes",
        ],
        "specs": {
            "Seat width": "18 inch",
            "Frame": "Chrome-plated steel",
            "Rear wheels": "24 inch mag",
            "Safe load": "100 kg",
            "Weight": "14 kg",
            "Folded": "Fits car boot",
        },
        "warranty": "1 Year",
        "certification": "ISO 13485:2016",
        "image_url": f"{IMG}/878409ddab591deff17d6fe531acead0981f943603c5b172f663a120c5c17405.jpeg",
        "featured": True,
    },
    {
        "slug": "glider-electric-wheelchair",
        "name": "Glider Foldable Electric Wheelchair",
        "sku": "SPS-EM-032",
        "category_slug": "emergency-mobility",
        "short_desc": "Foldable powered wheelchair with joystick control, 20 km range and airline-approved lithium battery.",
        "description": "The Glider electric wheelchair restores independence: a responsive joystick drives dual 250 W motors for up to 20 km on one charge, over a foldable aluminium frame you can lift into a hatchback. The lithium battery is airline-approved, so it travels where the user travels. Free home demo in Delhi NCR.",
        "price": 42000,
        "price_unit": "piece",
        "moq": "1 Piece",
        "features": [
            "Dual 250 W brushless motors",
            "Up to 20 km range per charge",
            "Airline-approved lithium battery",
            "Intuitive joystick controller",
            "Folds flat — lifts into a hatchback",
            "Flip-up armrests + detachable footrest",
        ],
        "specs": {
            "Motor": "2 × 250 W brushless",
            "Range": "20 km",
            "Battery": "24 V 12 Ah lithium",
            "Safe load": "120 kg",
            "Seat width": "18 inch",
            "Charge time": "6–8 hours",
        },
        "warranty": "2 Years",
        "certification": "ISO 13485:2016, CE",
        "image_url": f"{IMG}/fdd59519cc2fb7a8d9fe1231f05436a5e22e10f2290def6bab185b417a86b485.jpeg",
        "featured": False,
    },
]


async def seed() -> None:
    now = datetime.now(timezone.utc)
    for cat in CATEGORIES:
        await db.categories.replace_one({"slug": cat["slug"]}, cat, upsert=True)
    for prod in PRODUCTS:
        doc = {**prod, "in_stock": True, "created_at": now}
        await db.products.replace_one({"slug": prod["slug"]}, doc, upsert=True)
    print(f"Seeded {len(CATEGORIES)} categories and {len(PRODUCTS)} products")


if __name__ == "__main__":
    asyncio.run(seed())
